### ISSUE TITLE
Exception that kills the extension while loading a project

### ISSUE THREAD

**Issue by Nezrahm** [laurentkempe/GitDiffMargin#102]
I really like this extension but more often than not it seems to crash when opening up VS and loading a project. The message is this:

![image](https://cloud.githubusercontent.com/assets/8653358/20554666/bd1b7e02-b15d-11e6-803b-4ea1e84a71d6.png)

The error it's referring to is the following:

> System.Runtime.InteropServices.MarshalDirectiveException: StrictFilePathMarshaler must be used on a FilePath.
   at LibGit2Sharp.Core.StrictFilePathMarshaler.MarshalManagedToNative(Object managedObj)
   at System.StubHelpers.MngdRefCustomMarshaler.ConvertContentsToNative(IntPtr pMarshalState, Object& pManagedHome, IntPtr pNativeHome)
   at LibGit2Sharp.Core.NativeMethods.git_repository_discover(GitBuf buf, FilePath start_path, Boolean across_fs, FilePath ceiling_dirs)
   at LibGit2Sharp.Core.Proxy.<>c__DisplayClass39.<git_repository_discover>b__38(GitBuf buf)
   at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)
   at LibGit2Sharp.Core.Proxy.git_repository_discover(FilePath start_path)
   at LibGit2Sharp.Repository.Discover(String startingPath)
   at GitDiffMargin.Git.GitCommands.GetGitRepository(String path)
   at GitDiffMargin.DiffMarginFactoryBase.TryGetMarginCore(IWpfTextViewHost textViewHost)
   at GitDiffMargin.EditorDiffMarginFactory.CreateMargin(IWpfTextViewHost textViewHost, IWpfTextViewMargin containerMargin)
   at Microsoft.VisualStudio.Text.Utilities.ContainerMargin.<AddMargins>b__25_1(IWpfTextViewMarginProvider mp)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)

After this has happened, the extension is dead and I have to restart VS and hope for the best on the next try.

The project I'm opening when this usually happens is largeish and takes a while to load, is this some kind of timing problem (considering that it works sometimes)?

**Comment by Nezrahm** [comment]
Forgot to mention that I'm using Visual Studio 2015 (Update 3) and version 3.2.0.0 of the extension.

**Comment by laurentkempe** [comment]
@Nezrahm Thanks for the report! Could you show me the path of your repository please?

**Comment by Nezrahm** [comment]
There is nothing special about the path: The project resides in the folder C:\svnwork\tags\Tags1
And yes, this is a vanilla git repo even though the path mentions svn.

**Comment by laurentkempe** [comment]
Are you using some other extensions which might use LibGit2Sharp, so something related to Git?

**Comment by Nezrahm** [comment]
No, yours is the only thing related to Git (except for VS itself with the Team Explorer)

**Comment by laurentkempe** [comment]
Thanks. Searching for that exception StrictFilePathMarshaler  in LibGit2Sharp I came to read someone asked for doing another clone of the repository. Do you experience this problem only with that particular repository or others? If it is only with that one, could you try to clone it again? I never have seen that error and without being able to reproduce it I am just in the fog at the moment, so your help is greatly appreciated!

**Comment by Nezrahm** [comment]
Ok, so I tried the following.

* Cloned a new repo, same problem.
* Downloaded the GitDiffMargin master branch and ran the debugger. The error occurs and in this instance were it running Repository.Discover with the path "C:\svnwork\tags\Tags2\Source\DatabaseConnections.config". The exception details: 

> System.Runtime.InteropServices.MarshalDirectiveException occurred
  HResult=-2146233035
  Message=StrictFilePathMarshaler must be used on a FilePath.
  Source=GitVersionTask
  StackTrace:
       at LibGit2Sharp.Core.StrictFilePathMarshaler.MarshalManagedToNative(Object managedObj)
       at System.StubHelpers.MngdRefCustomMarshaler.ConvertContentsToNative(IntPtr pMarshalState, Object& pManagedHome, IntPtr pNativeHome)
       at LibGit2Sharp.Core.NativeMethods.git_repository_discover(GitBuf buf, FilePath start_path, Boolean across_fs, FilePath ceiling_dirs)
       at LibGit2Sharp.Core.Proxy.<>c__DisplayClass39.<git_repository_discover>b__38(GitBuf buf)
       at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)
       at LibGit2Sharp.Core.Proxy.git_repository_discover(FilePath start_path)
       at LibGit2Sharp.Repository.Discover(String startingPath)
       at GitDiffMargin.Git.GitCommands.GetGitRepository(String path) in C:\svnwork\GitDiffMargin-master\GitDiffMargin\Git\GitCommands.cs:line 288
  InnerException: 
* I then noticed the exception source, GitVersionTask, and found the following interesting discussion which seems pretty much bang on the problem: https://github.com/GitTools/GitVersion/issues/720
* The solution I'm working on contains GitVersion.CommandLine (v3.6.2) and GitVersionTask (v3.6.3), I updated both to 3.6.4 but the problem persists.

I don't have anymore time right now to continue perusing this but hopefully can you reproduce the problem if you add the GitVersionTask nuget package to a test project.

**Comment by laurentkempe** [comment]
Thanks @Nezrahm I also found the thread in GitTools/GitVersion#720

I plan so and so to remove the usage of LibGit2Sharp and LibGit and to use the git command line like Microsoft is doing it in Visual Studio 2017 RC, so this at the end should solve your issue!

**Comment by Nezrahm** [comment]
I just changed DiffMarginFactoryBase.TryGetMarginCore and added a try catch around GitCommands.GetGitRepository catching MarshalDirectiveException and returning null.

That seems to have solved/hidden the problem for me and that might be a short term solution.

Moving away from LibGit sounds like the proper way of handling it though.

**Comment by laurentkempe** [comment]
@Nezrahm Could you provide a Pull Request?
