### ISSUE TITLE
Breaks Edit.GoTo command

### ISSUE THREAD

**Issue by the-ress** [laurentkempe/GitDiffMargin#104]
1. Open a text file in VS 2015 (without Git Diff Margin installed)
2. Type `Edit.GoTo 5` into Command Window and press `Enter`
3. Cursor correctly jumps to line 5
4. Install Git Diff Margin
5. Type `Edit.GoTo 5` into Command Window and press `Enter`
6. Error appears in the Command Window: `Command "Edit.GoTo" does not accept arguments or switches.`

**Comment by laurentkempe** [comment]
Wow @the-ress thanks for the report! I have never used the Command Window to go to a line! I can't see how Git Diff Margin could break that, but I will have a look, sorry for the annoyance.

**Comment by the-ress** [comment]
I actually wanted to use it via `devenv.exe /Command`, to open a file at specified line, but there was another problem with it so I went with another solution. Still it might hit someone else (maybe with another command).

There's another extension that's causing this as well: [Open in External Browser](https://github.com/tunnelvisionlabs/OpenInExternalBrowser)

**Comment by laurentkempe** [comment]
@sharwell Any idea what could be the problem?

**Comment by sharwell** [comment]
I have no idea. That's super strange. Both of the extensions in question use my `TextViewCommandFilter` implementation.

I notice that the Go To Line (<kbd>Ctrl</kbd>+<kbd>G</kbd>) still works for me.

😕 I'm not able to reproduce this with just the Open in External Browser extension installed, so it does look to be something specific to Git Diff Margin.

**Comment by laurentkempe** [comment]
> I notice that the Go To Line (Ctrl+G) still works for me.

Yep same here!

**Comment by laurentkempe** [comment]
> I'm not able to reproduce this with just the Open in External Browser extension installed, so it does look to be something specific to Git Diff Margin.

Thanks @sharwell I will try after Christmas with Git Diff Margin! Merry Christmas 🎄 🎄 🎄

**Comment by sharwell** [comment]
@laurentkempe I was able to fix this in the end and submitted a pull request.

**Comment by laurentkempe** [comment]
@sharwell I am trying to compile from your branch on Visual Studio 2017 RC and get the following compilation error, any clue?

> 1>------ Build started: Project: GitDiffMargin, Configuration: Release Any CPU ------
1>  GitDiffMargin -> C:\@Projects\GitDiffMargin\GitDiffMargin\bin\Release\GitDiffMargin.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(953,5): error : CreatePkgDef : error : ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(953,5): error :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(953,5): error :    at System.Reflection.RuntimeModule.GetTypes()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(953,5): error :    at System.Reflection.Assembly.GetTypes()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(953,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.ProcessAssembly(String fileName, Hive hive, PkgDefContext context, Boolean register, RegistrationMode mode) in F:\dd\src\vssdk\VSIntegration\Tools\src\CreatePkgDef\CreatePkgDef.cs:line 261
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(953,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.DoCreatePkgDef(InputArguments inputArguments) in F:\dd\src\vssdk\VSIntegration\Tools\src\CreatePkgDef\CreatePkgDef.cs:line 164
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(953,5): error :    at Microsoft.VisualStudio.Tools.CreatePkgDef.Main(String[] arguments) in F:\dd\src\vssdk\VSIntegration\Tools\src\CreatePkgDef\CreatePkgDef.cs:line 85
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(953,5): error : Could not load file or assembly 'Microsoft.VisualStudio.Shell.Interop.8.0, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(953,5): error : 
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

I will try later on an older notebook which has Visual Studio 2015

**Comment by laurentkempe** [comment]
Yes, it is quite weird. Nevertheless, I have it working on Visual Studio 2015 so no worries!

**Comment by laurentkempe** [comment]
@the-ress You can try the latest release 3.2.1 - https://github.com/laurentkempe/GitDiffMargin/releases/download/v3.2.1/GitDiffMargin.vsix

Please let me know if it fixes the issue for you
