### ISSUE TITLE
Crash in GitDiffMargin

### ISSUE THREAD

**Issue by sharwell** [laurentkempe/GitDiffMargin#124]
The following issue was traced back to GitDiffMargin:
https://developercommunity.visualstudio.com/content/problem/34913/visusl-studio-crashes-after-clicking-on-line-in-fi.html

The following stack trace was provided with the crash report:

```
EventTime:3/23/2017 9:51:48 PM
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
at GitDiffMargin.ViewModel.EditorDiffViewModel.set_ShowPopup(Boolean)
at GitDiffMargin.ViewModel.EditorDiffViewModel..ctor(GitDiffMargin.Git.HunkRangeInfo, GitDiffMargin.Core.IMarginCore, System.Action`2)
at GitDiffMargin.ViewModel.EditorDiffMarginViewModel.CreateDiffViewModel(GitDiffMargin.Git.HunkRangeInfo)
at System.Linq.Enumerable+WhereSelectListIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
at GitDiffMargin.ViewModel.DiffMarginViewModelBase.HandleHunksChanged(System.Object, GitDiffMargin.Core.HunksChangedEventArgs)
at GitDiffMargin.ViewModel.EditorDiffMarginViewModel.HandleHunksChanged(System.Object, GitDiffMargin.Core.HunksChangedEventArgs)
at System.EventHandler`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Invoke(System.Object, System.__Canon)
at GitDiffMargin.Core.MarginCore.OnHunksChanged(System.Collections.Generic.IEnumerable`1)
at GitDiffMargin.Core.MarginCore+<>c__DisplayClass54_0.b__0()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
at System.Windows.Threading.DispatcherOperation.InvokeImpl()
at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Windows.Threading.DispatcherOperation.Invoke()
at System.Windows.Threading.Dispatcher.ProcessQueue()
at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by laurentkempe** [comment]
This issue is coming from Visual Studio developer community [report here](https://developercommunity.visualstudio.com/content/problem/34913/visusl-studio-crashes-after-clicking-on-line-in-fi.html)

**Comment by laurentkempe** [comment]
As Stan Thomas wrote yesterday "@Laurent Kempe sure that's fine with me. Everything is working and I'm happy. Great extension and I've come to rely on it."

@sharwell What do you think abou this "Is it possible to stop the file(s) in question being removed when VS2015 is uninstalled but file is still needed in VS2017? Seems that this will be quite a common occurrence as people move across to VS2017."
What could we do from the GitDiffMargin point of view because it is sure that uninstalling Vs 2015 won't stop removing that file!

**Comment by sharwell** [comment]
@laurentkempe Thanks for looking into this more. It sounds like a bug in the way VS 2015 and/or 2017 handles dependent extensions. I'll see what I can find out.

It looks like this issue has only caused one crash (per the "submit crash report" that shows up after a crash).

**Comment by sharwell** [comment]
Actually, the assembly in question is actually distributed as part of this project. [This attribute](https://github.com/laurentkempe/GitDiffMargin/blob/master/GitDiffMargin/Properties/AssemblyInfo.cs#L42-L45) is supposed to ensure this scenario doesn't occur.

**Comment by SamuelEnglard** [comment]
Just updated to version 3.5.1.48 and getting this crash repeatedly.

**Comment by SLaks** [comment]
For anyone else getting this error (Could not load file or assembly 'Tvl.VisualStudio.Text.Utility.10, Version=1.0.0.0, Culture=neutral, PublicKeyToken=eb42632606e9261f' or one of its dependencies. The system cannot find the file specified), uninstalling, then re-installing GitDiffMargin fixed it.
