### ISSUE TITLE
Could not load file or assembly Tvl.VisualStudio.Text.Utility.10

### ISSUE THREAD

**Issue by jcansdale** [laurentkempe/GitDiffMargin#196]
I've seen this a couple of times when opening a solution.

![image](https://user-images.githubusercontent.com/11719160/53749731-ed17e880-3e9f-11e9-81b4-a1956c2eaddc.png)

GitDiffMargin v3.9.3.49
Visual Studio 2019 Preview 3

```
System.IO.FileNotFoundException: Could not load file or assembly 'Tvl.VisualStudio.Text.Utility.10, Version=1.0.0.0, Culture=neutral, PublicKeyToken=eb42632606e9261f' or one of its dependencies.
The system cannot find the file specified. File name: 'Tvl.VisualStudio.Text.Utility.10, Version=1.0.0.0, Culture=neutral, PublicKeyToken=eb42632606e9261f'
at GitDiffMargin.Commands.CommandHandlerTextViewCreationListener.VsTextViewCreated(IVsTextView textViewAdapter) at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.<>c__DisplayClass430_0.<InstantiateVSTextViewCreationListenere>b__0()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call) --- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by sharwell** [comment]
It's a(nother) bug in the Visual Studio component model cache. Uninstalling/reinstalling Git Diff Margin will fix it.

**Comment by sharwell** [comment]
This dependency was removed in a235aee94b537c41a70978efe5db3889df4490ef
