### ISSUE TITLE
VS 2019 Installation Error

### ISSUE THREAD

**Issue by ringzer** [laurentkempe/GitDiffMargin#494]
## Versions
 - Git Diff Margin version: 3.12.1
 - Visual Studio version: 2019

## What happened
Installation Error - This extension is not installable on any currently installed products

### Logs
24/09/2021 10:26:10 - Microsoft VSIX Installer
24/09/2021 10:26:10 - -------------------------------------------
24/09/2021 10:26:10 - vsixinstaller.exe version:
24/09/2021 10:26:10 - 16.7.3069
24/09/2021 10:26:10 - -------------------------------------------
24/09/2021 10:26:10 - Command line parameters:
24/09/2021 10:26:10 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\F582553\Downloads\GitDiffMargin (1).vsix
24/09/2021 10:26:10 - -------------------------------------------
24/09/2021 10:26:10 - Microsoft VSIX Installer
24/09/2021 10:26:10 - -------------------------------------------
24/09/2021 10:26:11 - Initializing Install...
24/09/2021 10:26:11 - Extension Details...
24/09/2021 10:26:11 - 	Identifier         : GitDiffMargin..5ef9f816-d9ce-45cd-a8fa-cd67a807df0e
24/09/2021 10:26:11 - 	Name               : Git Diff Margin
24/09/2021 10:26:11 - 	Author             : Laurent Kempé
24/09/2021 10:26:11 - 	Version            : 3.12.1
24/09/2021 10:26:11 - 	Description        : Git Diff Margin displays live Git changes of the currently edited file on Visual Studio margin and scroll bar. Supports Visual Studio 2012 through Visual Studio 2022.
24/09/2021 10:26:11 - 	Locale             : en-US
24/09/2021 10:26:11 - 	MoreInfoURL        : https://github.com/laurentkempe/GitDiffMargin
24/09/2021 10:26:11 - 	InstalledByMSI     : False
24/09/2021 10:26:11 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
24/09/2021 10:26:11 - 
24/09/2021 10:26:11 - 	SignatureState     : Unsigned
24/09/2021 10:26:11 - 	Supported Products : 
24/09/2021 10:26:11 - 		Microsoft.VisualStudio.Community
24/09/2021 10:26:11 - 			Version : [11.0,17.0)
24/09/2021 10:26:11 - 		Microsoft.VisualStudio.Community
24/09/2021 10:26:11 - 			Version : [17.0,18.0)
24/09/2021 10:26:11 - 		Microsoft.VisualStudio.Pro
24/09/2021 10:26:11 - 			Version : [11.0,17.0)
24/09/2021 10:26:11 - 
24/09/2021 10:26:11 - 	References         : 
24/09/2021 10:26:11 - 	Prerequisites      : 
24/09/2021 10:26:11 - 		-------------------------------------------------------
24/09/2021 10:26:11 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
24/09/2021 10:26:11 - 		Name         : Visual Studio core editor
24/09/2021 10:26:11 - 		Version      : [15.0,18.0)
24/09/2021 10:26:11 - 
24/09/2021 10:26:11 - Signature Details...
24/09/2021 10:26:11 - 	Extension is not signed.
24/09/2021 10:26:11 - 
24/09/2021 10:26:11 - Searching for applicable products...
24/09/2021 10:26:11 - Found installed product - Global Location
24/09/2021 10:26:11 - Found installed product - Visual Studio Enterprise 2019
24/09/2021 10:26:13 - System.InvalidOperationException: VSHiveStub.exe failed: PkgdefManagement failed to create application: "0x80070003".
   at VSIXInstaller.LocationBasedSKU.SettingsManagerData.get_RegRootHiveOverride()
   at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.ExtensionService.GetExtensionEngineForApplicableSKU(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionService.TryAddSkuToValidSkuList(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension extension, List`1 validSKUs, Boolean isRepairSupported)
24/09/2021 10:26:13 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by laurentkempe** [comment]
Thanks for reporting your issue @ringzer 
First time I see such a problem 😕 
Any clue @sharwell ?

**Comment by ringzer** [comment]
I should clarify that I'm running Windows 10 on my company's network so it's entirely possible there is some unknown modification/restriction causing this.

However I have installed other VS extensions without issue. Often times things fail because external downloads are blocked for security reasons not it's not the case here.

The installation on my machine is managed by Windows App-V so perhaps the code you have to check what is installed doesn't check for the location used by App-V.

Is there anything you want me to check on my machine or registry?

**Comment by laurentkempe** [comment]
Thanks @ringzer I don't see anything to test more at the moment but if I get an idea I will get back to you
